output:
  - platform: ledc
    pin: ${pwm_fan_pin}
    id: ${device_name}_${pwm_fan_name}_output
    frequency: ${pwm_fan_frequency}

fan:
  - platform: speed
    output: ${device_name}_${pwm_fan_name}_output
    name: ${device_name_upper}.${pwm_fan_name}
    id: ${device_name}_${pwm_fan_name}
    speed_count: 5
    restore_mode: ALWAYS_OFF
