output:
  - platform: ledc
    pin: ${pwm_led_cc_4_pin}
    id: ${device_name}_${pwm_led_cc_4_name}_output
    frequency: ${pwm_led_frequency}
    max_power: ${pwm_led_cc_4_max_value}

light:
  - platform: monochromatic
    id: ${device_name}_${pwm_led_cc_4_name}
    name: ${device_name_upper}.${pwm_led_cc_4_name}
    output: ${device_name}_${pwm_led_cc_4_name}_output
    restore_mode: ALWAYS_OFF
    effects:
      # Use default parameters:
      - random:
      - random:
          name: "Slow Random Effect"
          transition_length: 10s
          update_interval: 10s
      - random:
          name: "Very Slow Random Effect"
          transition_length: 30s
          update_interval: 30s
      - pulse:
      - pulse:
          name: "Slow Pulse"
          transition_length: 10s      # defaults to 1s
          update_interval: 10s
      - pulse:
          name: "Very Slow Pulse"
          transition_length: 30s      # defaults to 1s
          update_interval: 30s
#number:       
#  - platform: template
#    min_value: "0.0"
#    max_value: "1.0"
#    step: "0.001"
#    id: ${device_name}_${pwm_led_cc_4_name}
#    name: ${device_name}.${pwm_led_cc_4_name}
#    optimistic: true
#    mode: slider
#    restore_value : false
#    initial_value: "0"
#    update_interval: "10s"
#    unit_of_measurement: ""
#    on_value:
#      - logger.log: "Set ${pwm_led_cc_4_name} level"
#      - output.set_level:
#           id: ${device_name}_${pwm_led_cc_4_name}_output
#           level: !lambda 'return x * ${pwm_led_cc_4_max_value};'
#      - output.ledc.set_frequency:
#          id: ${device_name}_${pwm_led_cc_4_name}_output
#          frequency: ${pwm_led_frequency}
#
#button:
#  - platform: template
#    name: ${device_name}.${pwm_led_cc_4_name}_on
#    id: ${device_name}_${pwm_led_cc_4_name}_on
#    on_press:
#      - number.set:
#          id: ${device_name}_${pwm_led_cc_4_name}
#          value: 1
#          
#  - platform: template
#    name: ${device_name}.${pwm_led_cc_4_name}_off
#    id: ${device_name}_${pwm_led_cc_4_name}_off
#    on_press:
#      - number.set:
#          id: ${device_name}_${pwm_led_cc_4_name}
#          value: 0
#          
#globals:
#  - id: ${device_name}_${pwm_led_cc_4_name}_is_on
#    type: bool
#    restore_value: no
#    initial_value: "false"  
#    
#switch:        
#  - platform: template
#    name: ${device_name}.${pwm_led_cc_4_name}_switch
#    id: ${device_name}_${pwm_led_cc_4_name}_switch
#    lambda: |-
#      return id(${device_name}_${pwm_led_cc_4_name}_is_on);
#    turn_on_action:
#      - button.press: ${device_name}_${pwm_led_cc_4_name}_on
#      - globals.set:
#          id: ${device_name}_${pwm_led_cc_4_name}_is_on
#          value: "true"
#    turn_off_action:
#      - button.press: ${device_name}_${pwm_led_cc_4_name}_off
#      - globals.set:
#          id: ${device_name}_${pwm_led_cc_4_name}_is_on
#          value: "false"