output:
  - platform: ledc
    pin: ${pwm_led_cc_10_pin}
    id: ${device_name}_${pwm_led_cc_10_name}_output
    frequency: ${pwm_led_frequency}

number:       
  - platform: template
    min_value: "0.0"
    max_value: ${pwm_led_cc_10_max_value}
    step: "0.01"
    id: ${device_name}_${pwm_led_cc_10_name}
    name: ${device_name}.${pwm_led_cc_10_name}
    optimistic: true
    mode: slider
    restore_value : false
    initial_value: "0"
    update_interval: "10s"
    unit_of_measurement: ""
    on_value:
      - logger.log: "Set ${pwm_led_cc_10_name} level"
      - output.set_level:
           id: ${device_name}_${pwm_led_cc_10_name}_output
           level: !lambda 'return x;'
      - output.ledc.set_frequency:
          id: ${device_name}_${pwm_led_cc_10_name}_output
          frequency: ${pwm_led_frequency}
          
button:
  - platform: template
    name: ${device_name}.${pwm_led_cc_10_name}_on
    id: ${device_name}_${pwm_led_cc_10_name}_on
    on_press:
      - number.set:
          id: ${device_name}_${pwm_led_cc_10_name}
          value: ${pwm_led_cc_10_max_value}
          
  - platform: template
    name: ${device_name}.${pwm_led_cc_10_name}_off
    id: ${device_name}_${pwm_led_cc_10_name}_off
    on_press:
      - number.set:
          id: ${device_name}_${pwm_led_cc_10_name}
          value: 0