substitutions:
  pwm_led_cc_1_pin: GPIO16
  pwm_led_cc_2_pin: GPIO17
  pwm_led_cc_3_pin: GPIO18
  pwm_led_cc_4_pin: GPIO19
  pwm_led_cc_5_pin: GPIO21
  pwm_led_cc_6_pin: GPIO22
  pwm_led_cc_7_pin: GPIO23
  pwm_led_cc_8_pin: GPIO25
  pwm_led_cc_9_pin: GPIO27
  pwm_led_cc_10_pin: GPIO26
  pwm_led_cc_11_pin: GPIO33
  pwm_led_cc_12_pin: GPIO32