packages:
  as_hydroponics_kit_as_ezo_ec: !include as_ezo_mqtt_sender_ec.yaml
  as_hydroponics_kit_as_ezo_ph: !include as_ezo_mqtt_sender_ph.yaml
  as_hydroponics_kit_as_ezo_rtd: !include as_ezo_mqtt_sender_rtd.yaml

button:

  # ENABLE/DISABLE ALL SENSORS
  - platform: template
    name: ${device_name_upper}.all.enable_mqtt
    id: ${device_name}_all_enable_mqtt
    on_press:
      - switch.turn_on: ${device_name}_ec_mqtt
      - switch.turn_on: ${device_name}_ph_mqtt
      - switch.turn_on: ${device_name}_rtd_mqtt
  
  - platform: template
    name: ${device_name_upper}.all.disable_mqtt
    id: ${device_name}_all_disable_mqtt
    on_press:
      - switch.turn_off: ${device_name}_ec_mqtt
      - switch.turn_off: ${device_name}_ph_mqtt
      - switch.turn_off: ${device_name}_rtd_mqtt