# Example configuration entry
sensor:
  - platform: bme280
    i2c_id: ${bme280_1_i2c_bus}
    temperature:
      name: "${device_name_upper}.${bme280_1_name}.temperature"
      id: ${device_name}_${bme280_1_name}_temperature
      oversampling: ${bme280_1_oversampling}
    pressure:
      name: "${device_name_upper}.${bme280_1_name}.pressure"
      id: ${device_name}_${bme280_1_name}_pressure
    humidity:
      name: "${device_name_upper}.${bme280_1_name}.humidity"
      id: ${device_name}_${bme280_1_name}_humidity 
    address: ${bme280_1_adress}
    update_interval: ${bme280_1_update_interval}