# Example configuration entry
sensor:
  # BMP280 (later should be BME280 with humidity)
  - platform: bmp280
    i2c_id: ${bmp280_2_i2c_bus}
    temperature:
      name: "${device_name_upper}.${bmp280_2_name}.temperature"
      id: ${device_name}_${bmp280_2_name}_temperature
      oversampling: ${bme280_2_oversampling}
    pressure:
      name: "${device_name_upper}.${bmp280_2_name}.pressure"
      id: ${device_name}_${bmp280_2_name}_pressure
    address: ${bme280_2_adress}
    update_interval: ${bme280_2_update_interval}