sensor:
  - platform: adc
    pin: ${sensor_current_hall_1_pin}
    name: "${device_name_upper}.${sensor_current_hall_1_name}.current"
    id: ${device_name}_${sensor_current_hall_1_name}_current
    unit_of_measurement: A
    update_interval: 1s
    attenuation: auto  # auto, 0db, 2.5db, 6db, 11db
    filters:
      - sliding_window_moving_average:
          window_size: 20
          send_every: 10
      - calibrate_linear:
          - 1.65 -> 0.0
          - 3.3 -> 7.35
      - lambda: |-
          if(x < 0)
            return 0.0;
          else
            return x;