sensor:
  - platform: dallas
    address: XXXXXXXXXXXXXX
    name: "${device_name_upper}.${sensor_dallas_1_name}.temperature"
    id: ${device_name}_${sensor_dallas_1_name}_temperature
    dallas_id : ${sensor_dallas_4_hub_id}