sensor:
  - platform: dallas
    address: 0xca02109245ad2528
    name: "${device_name_upper}.${sensor_dallas_11_name}.temperature"
    id: ${device_name}_${sensor_dallas_11_name}_temperature
    dallas_id : ${sensor_dallas_11_hub_id}
    force_update: ${sensor_dallas_11_force_update}