sensor:
  - platform: dallas
    address: ${dallas_6_adress}
    name: "${device_name_upper}.${sensor_dallas_6_name}.temperature"
    id: ${device_name}_${sensor_dallas_6_name}_temperature
    dallas_id : ${sensor_dallas_6_hub_id}
    force_update: ${sensor_dallas_6_force_update}