sensor:
  - platform: dallas
    address: 0xab02109245afe928
    name: "${device_name_upper}.${sensor_dallas_4_name}.temperature"
    id: ${device_name}_${sensor_dallas_4_name}_temperature
    dallas_id : ${sensor_dallas_4_hub_id}