sensor:
  - platform: dallas
    address: ${dallas_13_adress}
    name: "${device_name_upper}.${sensor_dallas_13_name}.temperature"
    id: ${device_name}_${sensor_dallas_13_name}_temperature
    dallas_id : ${sensor_dallas_13_hub_id}
    force_update: ${sensor_dallas_13_force_update}