sensor:
  - platform: dallas
    address: 0x3a02149245a4d828
    name: "${device_name_upper}.${sensor_dallas_17_name}.temperature"
    id: ${device_name}_${sensor_dallas_17_name}_temperature
    dallas_id : ${sensor_dallas_17_hub_id}
    force_update: ${sensor_dallas_17_force_update}