sensor:
  - platform: dallas
    address: ${dallas_1_adress}
    name: "${device_name_upper}.${sensor_dallas_1_name}.temperature"
    id: ${device_name}_${sensor_dallas_1_name}_temperature
    dallas_id : ${sensor_dallas_1_hub_id}
    force_update: ${sensor_dallas_1_force_update}