sensor:
  - platform: dallas
    address: ${dallas_5_adress}
    name: "${device_name_upper}.${sensor_dallas_5_name}.temperature"
    id: ${device_name}_${sensor_dallas_5_name}_temperature
    dallas_id : ${sensor_dallas_5_hub_id}
    force_update: ${sensor_dallas_5_force_update}