sensor:
  - platform: dallas
    address: ${dallas_2_adress}
    name: "${device_name_upper}.${sensor_dallas_2_name}.temperature"
    id: ${device_name}_${sensor_dallas_2_name}_temperature
    dallas_id : ${sensor_dallas_2_hub_id}
    force_update: ${sensor_dallas_2_force_update}