sensor:
  - platform: dallas
    address: ${dallas_14_adress}
    name: "${device_name_upper}.${sensor_dallas_14_name}.temperature"
    id: ${device_name}_${sensor_dallas_14_name}_temperature
    dallas_id : ${sensor_dallas_14_hub_id}
    force_update: ${sensor_dallas_14_force_update}