sensor:
  - platform: dallas
    address: ${dallas_16_adress}
    name: "${device_name_upper}.${sensor_dallas_16_name}.temperature"
    id: ${device_name}_${sensor_dallas_16_name}_temperature
    dallas_id : ${sensor_dallas_16_hub_id}
    force_update: ${sensor_dallas_17_force_update}