sensor:
  - platform: dallas
    address: XXXXXXXXXXXXXX
    name: "${device_name_upper}.${sensor_dallas_5_name}.temperature"
    id: ${device_name}_${sensor_dallas_5_name}_temperature
    dallas_id : ${sensor_dallas_5_hub_id}