sensor:
  - platform: dallas
    address: 0x500316885dc6ff28
    name: "${device_name_upper}.${sensor_dallas_1_name}.temperature"
    id: ${device_name}_${sensor_dallas_1_name}_temperature
    dallas_id : ${sensor_dallas_1_hub_id}