sensor:
  - platform: dallas
    address: {dallas_7_adress}
    name: "${device_name_upper}.${sensor_dallas_7_name}.temperature"
    id: ${device_name}_${sensor_dallas_7_name}_temperature
    dallas_id : ${sensor_dallas_7_hub_id}
    force_update: ${sensor_dallas_7_force_update}