sensor:
  - platform: dallas
    address: 0x5502109245a52d28
    name: "${device_name_upper}.${sensor_dallas_12_name}.temperature"
    id: ${device_name}_${sensor_dallas_12_name}_temperature
    dallas_id : ${sensor_dallas_12_hub_id}