sensor:
  - platform: dallas
    address: ${dallas_9_adress}
    name: "${device_name_upper}.${sensor_dallas_9_name}.temperature"
    id: ${device_name}_${sensor_dallas_9_name}_temperature
    dallas_id : ${sensor_dallas_9_hub_id}
    force_update: ${sensor_dallas_9_force_update}