sensor:
  - platform: dallas
    address: dallas_8_adress}
    name: "${device_name_upper}.${sensor_dallas_8_name}.temperature"
    id: ${device_name}_${sensor_dallas_8_name}_temperature
    dallas_id : ${sensor_dallas_8_hub_id}
    force_update: ${sensor_dallas_8_force_update}