sensor:
  - platform: dallas
    address: 0xe402109245b42d28
    name: "${device_name_upper}.${sensor_dallas_2_name}.temperature"
    id: ${device_name}_${sensor_dallas_2_name}_temperature
    dallas_id : ${sensor_dallas_2_hub_id}