- id: looper
  alias: looper
  initial_state: true
  mode: restart
  trigger:
  - id: trigger_looper
    platform: state
    entity_id: input_boolean.activate_looper
    to: 'on'
  condition:
  - condition: trigger
    id: trigger_looper
  action:
  - repeat:
      while:
      - condition: or
        conditions:
        - condition: template
          value_template: '{% if is_state(''input_boolean.activate_looper'', ''on'')
            %} true {% else %} false {% endif %}'
      sequence:
      - service: persistent_notification.create
        data_template:
          title: Looper {{now().timestamp()|timestamp_local}}
          message: Looper has triggered.
      - delay: 00:00:01
- id: '1670317243362'
  alias: nodered_restart
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
  mode: restart
- id: '1670317667056'
  alias: watchdog_notification_example
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: '#Info- #Status'
      notification_id: watchdog_notification_example
      message: Daily Life Sign.
  mode: restart
- id: '1672134136129'
  alias: watchdog_led_temperature
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition:
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.pcs1_led_panel_max_temperature
      above: '50'
    - condition: numeric_state
      entity_id: sensor.pcs1_growth_chamber_average_temperature
      above: '26'
    - condition: numeric_state
      entity_id: sensor.pcs1_kin_dallas_4_temperature
      above: '45'
    - condition: state
      entity_id: sensor.pcs1_max_temperature
      state: '50'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id:
      - sensor.pcs1_main_power
  mode: single
- id: '1674218687970'
  alias: watchdog_nodered_heartbeat_restart
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /10
  condition:
  - condition: state
    entity_id: input_boolean.node_red_heartbeat
    state: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.node_red_heartbeat
  mode: single
- id: '1674833598388'
  alias: automation_power_supply_control
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /10
  condition:
  - condition: state
    entity_id: input_boolean.pcs1_automation_power_supply_active
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: schedule.pcs1_main_power_schedule
        state: 'off'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.pcs1_main
    default: []
  mode: restart
- id: '1685090732927'
  alias: watchdog_nodered_heartbeat_shutdown
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /10
  condition:
  - condition: state
    entity_id: input_boolean.node_red_heartbeat
    state: 'on'
    for:
      hours: 0
      minutes: 10
      seconds: 0
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pcs1_kin_stepper_enable_motor
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pcs1_main
  mode: single
- id: '1685090902166'
  alias: watchdog_nodered_heartbeat
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /10
  condition:
  - condition: state
    entity_id: input_boolean.node_red_heartbeat
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.node_red_heartbeat
  mode: single
