- id: looper
  alias: looper
  initial_state: true
  mode: restart
  trigger:
  - id: trigger_looper
    platform: state
    entity_id: input_boolean.activate_looper
    to: 'on'
  condition:
  - condition: trigger
    id: trigger_looper
  action:
  - repeat:
      while:
      - condition: or
        conditions:
        - condition: template
          value_template: '{% if is_state(''input_boolean.activate_looper'', ''on'')
            %} true {% else %} false {% endif %}'
      sequence:
      - service: persistent_notification.create
        data_template:
          title: Looper {{now().timestamp()|timestamp_local}}
          message: Looper has triggered.
      - delay: 00:00:01
- id: '1670317243362'
  alias: nodered_restart
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
  mode: restart
- id: '1670317667056'
  alias: watchdog_notification_example
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: '#Info- #Status'
      notification_id: watchdog_notification_example
      message: Daily Life Sign.
  mode: restart
- id: '1672134136129'
  alias: Watchdogled
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /30
  condition:
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: sensor.pcs1_led_panel_max_temperature
      above: '45'
    - condition: numeric_state
      entity_id: sensor.pcs1_growth_chamber_average_temperature
      above: '26'
  action:
  - service: homeassistant.turn_off
    data: {}
    target:
      entity_id: input_boolean.activate_led_automation
  mode: single
