# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_bot_api_key
#    allowed_chat_ids: 
#      - !secret telegram_bot_api_chat_id
#      - !secret telegram_bot_info_group_id
#      - !secret telegram_bot_chat_id_1
#      
#notify:
#    - platform: telegram
#      name: telegram_info
#      chat_id: !secret telegram_bot_info_group_id

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 7
  purge_interval: 1
  commit_interval: 30 

history:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  ssl: false
  max_retries: 3
  default_measurement: state  
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - input_number
      - button
      
switch:
  - platform: momentary
    name: Camera Snapshots
    mode: on
    toggle_for: 1
    
input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off
  
  activate_looper:
    name: Activate looper
    
  activate_kinematics_automation:
    name: Activate kinematics automation
  
  camera_sequence_taking_photos:
    name: Camera sequence taking photos
    
  activate_led_automation:
    name: Activate led automation
    
# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number:
  
# Example configuration.yaml entry
sensor:
  - platform: average
    name: 'pcs1.led_panel_fan_80mm.average_temperature'
    entities:
      - sensor.pcs1_led1_dallas_fan_140mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_4_temperature
      
  - platform: average
    name: 'pcs1.led_panel.fan_140mm.average_temperature'
    entities:
      - sensor.pcs1_led1_dallas_fan_80mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_4_temperature
      
  - platform: average
    name: 'pcs1.led_panel.average_temperature'
    duration: 00:01:00
    entities:
      - sensor.pcs1_led_panel_fan_140mm_average_temperature
      - sensor.pcs1_led_panel_fan_80mm_average_temperature

  - platform: min_max
    type: max
    name: "pcs1.led_panel.max_temperature"
    entity_ids:
      - sensor.pcs1_led1_dallas_fan_80mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_4_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_4_temperature
  
  - platform: average
    name: 'pcs1.led_panel.average_max_temperature'
    duration: 00:01:00
    entities:
      - sensor.pcs1_led_panel_max_temperature
        
  - platform: average
    name: 'pcs1.outside.average_temperature'
    duration: 00:01:00
    entities:
      - sensor.pcs1_pwm_dallas_2_temperature
  
  - platform: average
    name: 'pcs1.electronics_area.average_temperature'
    duration: 00:01:00
    entities:
      - sensor.pcs1_pwm_dallas_1_temperature
    
  - platform: average
    name: 'pcs1.growth_chamber.average_temperature'
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_temperature
      - sensor.pcs1_cam3_bme280_1_temperature
      - sensor.pcs1_cam4_bme280_1_temperature
      - sensor.pcs1_cam5_bme280_1_temperature
      - sensor.pcs1_cam6_bme280_1_temperature
      
  - platform: average
    name: 'pcs1.growth_chamber.average_humidity'
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_humidity
      - sensor.pcs1_cam3_bme280_1_humidity
      - sensor.pcs1_cam4_bme280_1_humidity
      - sensor.pcs1_cam5_bme280_1_humidity
      - sensor.pcs1_cam6_bme280_1_humidity
  
  - platform: average
    name: 'pcs1.growth_chamber.average_pressure'
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_pressure
      - sensor.pcs1_cam3_bme280_1_pressure
      - sensor.pcs1_cam4_bme280_1_pressure
      - sensor.pcs1_cam5_bme280_1_pressure
      - sensor.pcs1_cam6_bme280_1_pressure
      
  - platform: average
    name: 'pcs1.growth_chamber.average_illuminance'
    duration: 00:00:5
    entities:
      - sensor.pcs1_cam1_bh1750_1_illuminance
      - sensor.pcs1_cam3_bh1750_1_illuminance
      - sensor.pcs1_cam4_bh1750_1_illuminance
      - sensor.pcs1_cam5_bh1750_1_illuminance
      - sensor.pcs1_cam6_bh1750_1_illuminance
      
  - platform: min_max
    type: max
    name: "pcs1.led1.growth_chamber.max_illuminance"
    entity_ids:
      - sensor.pcs1_cam1_bh1750_1_illuminance
      - sensor.pcs1_cam3_bh1750_1_illuminance
      - sensor.pcs1_cam4_bh1750_1_illuminance
      - sensor.pcs1_cam5_bh1750_1_illuminance
      - sensor.pcs1_cam6_bh1750_1_illuminance
      
  - platform: average
    name: 'pcs1.growth_chamber.average_max_illuminance'
    duration: 00:00:5
    entities:
      - sensor.pcs1_led1_growth_chamber_max_illuminance