# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

api:

# Example configuration.yaml entry
#telegram_bot:
#  - platform: polling
#    api_key: !secret telegram_bot_api_key
#    allowed_chat_ids:
#      - !secret telegram_bot_api_chat_id
#      - !secret telegram_bot_info_group_id
#      - !secret telegram_bot_chat_id_1
#
#notify:
#    - platform: telegram
#      name: telegram_info
#      chat_id: !secret telegram_bot_info_group_id

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 60
  purge_interval: 1
  commit_interval: 30

history:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  ssl: false
  max_retries: 3
  default_measurement: state
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - input_number
      - button

switch:
  - platform: momentary
    name: Camera Snapshots
    mode: on
    toggle_for: 1

input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off

  activate_looper:
    name: Activate looper

  pcs1_automation_main_active:
    name: pcs1.automation_main.active

  pcs1_automation_kinematics_active:
    name: pcs1.automation_kinematics.active

  pcs1_automation_pump_active:
    name: pcs1.pump_automation.active

  pcs1_automation_led_active:
    name: pcs1.automation_led.active
 
  pcs1_automation_led_safety_active:
    name: pcs1.automation_led_safety.active
    
  pcs1_automation_fan_active:
    name: pcs1.automation_fan.active
    
  pcs1_automation_daynight_active:
    name: pcs1.automation_daynight.active
    
  pcs1_automation_daylength_active:
    name: pcs1.automation_daylength.active
    
  pcs1_automation_daylight_active:
    name: pcs1.automation_daylight.active
  
  pcs1_automation_seasonlight_active:
    name: pcs1.automation_seasonlight.active

  
    
  pcs1_automation_camera_active:
    name: pcs1.automation_camera.active

  pcs1_mode_maintenance_active:
    name: pcs1.maintenance_mode.active

  pcs1_cameras_enabled:
    name: pcs1.cameras_enabled
  
  pcs1_cameras_plant1_enabled:
    name: pcs1.cameras_plant1_enabled
  
  pcs1_cameras_plant2_enabled:
    name: pcs1.cameras_plant2_enabled
  
  pcs1_cameras_plant3_enabled:
    name: pcs1.cameras_plant3_enabled
  
  pcs1_cameras_plant4_enabled:
    name: pcs1.cameras_plant4_enabled
  
  pcs1_cameras_plant5_enabled:
    name: pcs1.cameras_plant5_enabled
  
  pcs1_cameras_plant6_enabled:
    name: pcs1.cameras_plant6_enabled

  pcs1_cameras_cam1_enabled:
    name: pcs1.cameras_cam1_enabled
  
  pcs1_cameras_cam2_enabled:
    name: pcs1.cameras_cam2_enabled
  
  pcs1_cameras_cam3_enabled:
    name: pcs1.cameras_cam3_enabled
  
  pcs1_cameras_cam4_enabled:
    name: pcs1.cameras_cam4_enabled
  
  pcs1_cameras_cam5_enabled:
    name: pcs1.cameras_cam5_enabled
  
  pcs1_cameras_cam6_enabled:
    name: pcs1.cameras_cam6_enabled  

  pcs1_cameras_cam7_enabled:
    name: pcs1.cameras_cam7_enabled  
  
  pcs1_led_white_active:
    name: pcs1.led_white_active
  
  pcs1_led_red_active:
    name: pcs1.led_red_active

  pcs1_led_blue_active:
    name: pcs1.led_blue_active

  pcs1_led_green_active:
    name: pcs1.led_green_active

  pcs1_led_uv_active:
    name: pcs1.led_uv_active
    
  pcs1_led_white_camera_mode_active:
    name: pcs1.led_white_camera_mode_active
  
  pcs1_led_red_camera_mode_active:
    name: pcs1.led_red_camera_mode_active

  pcs1_led_blue_camera_mode_active:
    name: pcs1.led_blue_camera_mode_active

  pcs1_led_green_camera_mode_active:
    name: pcs1.led_green_camera_mode_active

  pcs1_led_uv_camera_mode_active:
    name: pcs1.led_uv_camera_mode_active
    
  pcs1_led_uv_enabled:
    name: pcs1.led_uv_enabled
  
  pcs1_daytime_day_active:
    name: pcs1.daytime_day_active 
  
  
  ##########################################################
  ## old entities for test automations in home assistant...
  ##########################################################

  activate_kinematics_automation:
    name: Activate kinematics automation

  camera_sequence_taking_photos:
    name: Camera sequence taking photos

  activate_led_automation:
    name: Activate led automation

  auto:
    name: automation.main.activate

  ##########################################################
  ##########################################################
  ##########################################################

input_select:
  pcs1_kinematics_automation_delay_day:
    name: pcs1.kinematics_automation_delay_day
    options:
      - DELAY_DAY_0
      - DELAY_DAY_1
      - DELAY_DAY_5
      - DELAY_DAY_10
      - DELAY_DAY_20
    initial: DELAY_DAY_0
    
  pcs1_kinematics_automation_delay_night:
    name: pcs1.kinematics_automation_delay_night
    options:
      - DELAY_NIGHT_0
      - DELAY_NIGHT_1
      - DELAY_NIGHT_5
      - DELAY_NIGHT_10
      - DELAY_NIGHT_20
    initial: DELAY_NIGHT_0

  pcs1_led_white_daylight_function:
    name: pcs1.led_white_daylight_function
    options:
      - USER_VALUES
      - CONSTANT
      - PYRAMIDAL
      - INVERSE_PYRAMIDAL
      - SINE
      - COSINE
      - VALLEY
      - VALLEY_NARROW
      - PLATEAU
      - PLATEAU_LEFT
      - PLATEAU_MIDDLE
      - PLATEAU_RIGHT
      - PEAK_LEFT
      - PEAK_MIDDLE
      - PEAK_RIGHT
    initial: PLATEAU
    
  pcs1_led_red_daylight_function:
    name: pcs1.led_red_daylight_function
    options:
      - USER_VALUES
      - CONSTANT
      - PYRAMIDAL
      - INVERSE_PYRAMIDAL
      - SINE
      - COSINE
      - VALLEY
      - VALLEY_NARROW
      - PLATEAU
      - PLATEAU_LEFT
      - PLATEAU_MIDDLE
      - PLATEAU_RIGHT
      - PEAK_LEFT
      - PEAK_MIDDLE
      - PEAK_RIGHT
    initial: PLATEAU

  pcs1_led_blue_daylight_function:
    name: pcs1.led_blue_daylight_function
    options:
      - USER_VALUES
      - CONSTANT
      - PYRAMIDAL
      - INVERSE_PYRAMIDAL
      - SINE
      - COSINE
      - VALLEY
      - VALLEY_NARROW
      - PLATEAU
      - PLATEAU_LEFT
      - PLATEAU_MIDDLE
      - PLATEAU_RIGHT
      - PEAK_LEFT
      - PEAK_MIDDLE
      - PEAK_RIGHT
    initial: PLATEAU

  pcs1_led_green_daylight_function:
    name: pcs1.led_green_daylight_function
    options:
      - USER_VALUES
      - CONSTANT
      - PYRAMIDAL
      - INVERSE_PYRAMIDAL
      - SINE
      - COSINE
      - VALLEY
      - VALLEY_NARROW
      - PLATEAU
      - PLATEAU_LEFT
      - PLATEAU_MIDDLE
      - PLATEAU_RIGHT
      - PEAK_LEFT
      - PEAK_MIDDLE
      - PEAK_RIGHT
    initial: PLATEAU

  pcs1_led_uv_daylight_function:
    name: pcs1.led_uv_daylight_function
    options:
      - USER_VALUES
      - CONSTANT
      - PYRAMIDAL
      - INVERSE_PYRAMIDAL
      - SINE
      - COSINE
      - VALLEY
      - VALLEY_NARROW
      - PLATEAU
      - PLATEAU_LEFT
      - PLATEAU_MIDDLE
      - PLATEAU_RIGHT
      - PEAK_LEFT
      - PEAK_MIDDLE
      - PEAK_RIGHT
    initial: PLATEAU
    
  pcs1_daylength_function:
    name: pcs1.daylength_function
    options:
      - DAYLENGTH_FUNCTION_CONSTANT
      - DAYLENGTH_FUNCTION_LINEAR
      - DAYLENGTH_FUNCTION_SINE
      - DAYLENGTH_FUNCTION_SPLINE
    initial: DAYLENGTH_FUNCTION_CONSTANT

# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number:
  time_diff:
    name: time_diff
    initial: 0
    min: -3
    max: 3
    step: 1
  
  pcs1_kinematics_pinionwheel_count_difference_error:
    name: pcs1.kinematics_pinionwheel_count_difference_error
    initial: 5
    min: 0
    max: 10
    step: 1 
    
  pcs1_fan_power:
    name: pcs1.fan_power
    initial: 0
    min: 0
    max: 100
    step: 1 
  
  pcs1_led_power_safety_factor:
    name: pcs1.led_power_safety_factor
    initial: 1.0
    min: 0
    max: 1
    step: 0.01
  
  pcs1_led_white_brightness:
    name: pcs1.led_white_brightness
    initial: 0
    min: 0
    max: 100
    step: 1
  
  pcs1_led_white_brightness_min:
    name: pcs1.led_white_brightness_min
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_white_brightness_max:
    name: pcs1.led_white_brightness_max
    initial: 0
    min: 0
    max: 100
    step: 1
  
  pcs1_led_white_brightness_max_winter:
    name: pcs1.led_white_brightness_max_winter
    initial: 0
    min: 0
    max: 100
    step: 1
  
  pcs1_led_white_brightness_max_summer:
    name: pcs1.led_white_brightness_max_summer
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_white_brightness_camera_mode:
    name: pcs1.led_white_brightness_camera_mode
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_red_brightness:
    name: pcs1.led_red_brightness
    initial: 0
    min: 0
    max: 100
    step: 1

  pcs1_led_red_brightness_min:
    name: pcs1.led_red_brightness_min
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_red_brightness_max:
    name: pcs1.led_red_brightness_max
    initial: 0
    min: 0
    max: 100
    step: 1

  pcs1_led_red_brightness_max_winter:
    name: pcs1.led_red_brightness_max_winter
    initial: 0
    min: 0
    max: 100
    step: 1

  pcs1_led_red_brightness_max_summer:
    name: pcs1.led_red_brightness_max_summer
    initial: 0
    min: 0
    max: 100
    step: 1
  
  pcs1_led_red_brightness_camera_mode:
    name: pcs1.led_red_brightness_camera_mode
    initial: 0
    min: 0
    max: 100
    step: 1
  
  pcs1_led_blue_brightness:
    name: pcs1.led_blue_brightness
    initial: 0
    min: 0
    max: 100
    step: 1  

  pcs1_led_blue_brightness_min:
    name: pcs1.led_blue_brightness_min
    initial: 0
    min: 0
    max: 100
    step: 1 
    
  pcs1_led_blue_brightness_max:
    name: pcs1.led_blue_brightness_max
    initial: 0
    min: 0
    max: 100
    step: 1 

    
  pcs1_led_blue_brightness_max_winter:
    name: pcs1.led_blue_brightness_max_winter
    initial: 0
    min: 0
    max: 100
    step: 1 

  pcs1_led_blue_brightness_max_summer:
    name: pcs1.led_blue_brightness_max_summer
    initial: 0
    min: 0
    max: 100
    step: 1 
  
  pcs1_led_blue_brightness_camera_mode:
    name: pcs1.led_blue_brightness_camera_mode
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_green_brightness:
    name: pcs1.led_green_brightness
    initial: 0
    min: 0
    max: 100
    step: 1  

  pcs1_led_green_brightness_min:
    name: pcs1.led_green_brightness_min
    initial: 0
    min: 0
    max: 100
    step: 1  
    
  pcs1_led_green_brightness_max:
    name: pcs1.led_green_brightness_max
    initial: 0
    min: 0
    max: 100
    step: 1  
    
  pcs1_led_green_brightness_max_winter:
    name: pcs1.led_green_brightness_max_winter
    initial: 0
    min: 0
    max: 100
    step: 1     

  pcs1_led_green_brightness_max_summer:
    name: pcs1.led_green_brightness_max_summer
    initial: 0
    min: 0
    max: 100
    step: 1  
    
  pcs1_led_green_brightness_camera_mode:
    name: pcs1.led_green_brightness_camera_mode
    initial: 0
    min: 0
    max: 100
    step: 1  

  pcs1_led_uv_brightness:
    name: pcs1.led_uv_brightness
    initial: 0
    min: 0
    max: 100
    step: 1    

  pcs1_led_uv_brightness_min:
    name: pcs1.led_uv_brightness_min
    initial: 0
    min: 0
    max: 100
    step: 1 
    
  pcs1_led_uv_brightness_max:
    name: pcs1.led_uv_brightness_max
    initial: 0
    min: 0
    max: 100
    step: 1  

  pcs1_led_uv_brightness_max_winter:
    name: pcs1.led_uv_brightness_max_winter
    initial: 0
    min: 0
    max: 100
    step: 1

  pcs1_led_uv_brightness_max_summer:
    name: pcs1.led_uv_brightness_max_summer
    initial: 0
    min: 0
    max: 100
    step: 1
    
  pcs1_led_uv_brightness_camera_mode:
    name: pcs1.led_uv_brightness_camera_mode
    initial: 0
    min: 0
    max: 100
    step: 1 

input_text:
  pcs1_plant1_name:
    name: pcs1.plant1_name
    initial: empty_plantgear
  pcs1_plant2_name:
    name: pcs1.plant2_name
    initial: empty_plantgear
  pcs1_plant3_name:
    name: pcs1.plant3_name
    initial: empty_plantgear
  pcs1_plant4_name:
    name: pcs1.plant4_name
    initial: empty_plantgear
  pcs1_plant5_name:
    name: pcs1.plant5_name
    initial: empty_plantgear
  pcs1_plant6_name:
    name: pcs1.plant6_name
    initial: empty_plantgear    

input_datetime:
  #both_date_and_time:
  #  name: Input with both date and time
  #  has_date: true
  #  has_time: true
  #only_date:
  #  name: Input with only date
  #  has_date: true
  #  has_time: false
  
  
  pcs1_daytime_day_start:
    name: pcs1.daytime_day_start
    has_date: false
    has_time: true
  
  pcs1_daytime_day_end:
    name: pcs1.daytime_day_end
    has_date: false
    has_time: true
  
  pcs1_daytime_day_length:
    name: pcs1.daytime_day_length
    has_date: false
    has_time: true
  
  
  
  ## old entities for testing purposes
  date_test:
    name: date_test
    has_date: true
    has_time: true

  day_length_delay:
    name: day_length_delay
    has_date: false
    has_time: true

  day_length:
    name: day_length
    has_date: false
    has_time: true
  day_start:
    name: day_start
    has_date: false
    has_time: true
  day_middle:
    name: day_middle
    has_date: false
    has_time: true
  day_end:
    name: day_end
    has_date: false
    has_time: true

# Example configuration.yaml entry
sensor:
  - platform: time_date
    display_options:
      - "time"
      - "date"
      - "date_time"
      - "date_time_utc"
      - "date_time_iso"
      - "time_date"
      - "time_utc"
      - "beat"
  - platform: average
    name: "pcs1.led_panel_fan_80mm.average_temperature"
    entities:
      - sensor.pcs1_led1_dallas_fan_140mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_4_temperature

  - platform: average
    name: "pcs1.led_panel.fan_140mm.average_temperature"
    entities:
      - sensor.pcs1_led1_dallas_fan_80mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_4_temperature

  - platform: average
    name: "pcs1.led_panel.average_temperature"
    duration: 00:01:00
    entities:
      - sensor.pcs1_led_panel_fan_140mm_average_temperature
      - sensor.pcs1_led_panel_fan_80mm_average_temperature

  - platform: min_max
    type: max
    name: "pcs1.led_panel.max_temperature"
    entity_ids:
      - sensor.pcs1_led1_dallas_fan_80mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_80mm_4_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_1_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_2_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_3_temperature
      - sensor.pcs1_led1_dallas_fan_140mm_4_temperature

  - platform: average
    name: "pcs1.led_panel.average_max_temperature"
    duration: 00:01:00
    entities:
      - sensor.pcs1_led_panel_max_temperature

  - platform: average
    name: "pcs1.outside.average_temperature"
    duration: 00:01:00
    entities:
      - sensor.pcs1_pwm_dallas_2_temperature

  - platform: average
    name: "pcs1.electronics_area.average_temperature"
    duration: 00:01:00
    entities:
      - sensor.pcs1_pwm_dallas_1_temperature

  - platform: average
    name: "pcs1.growth_chamber.average_temperature"
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_temperature
      - sensor.pcs1_cam3_bme280_1_temperature
      - sensor.pcs1_cam4_bme280_1_temperature
      - sensor.pcs1_cam5_bme280_1_temperature
      - sensor.pcs1_cam6_bme280_1_temperature

  - platform: average
    name: "pcs1.growth_chamber.average_humidity"
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_humidity
      - sensor.pcs1_cam3_bme280_1_humidity
      - sensor.pcs1_cam4_bme280_1_humidity
      - sensor.pcs1_cam5_bme280_1_humidity
      - sensor.pcs1_cam6_bme280_1_humidity

  - platform: average
    name: "pcs1.growth_chamber.average_pressure"
    duration: 00:01:00
    entities:
      - sensor.pcs1_cam1_bme280_1_pressure
      - sensor.pcs1_cam3_bme280_1_pressure
      - sensor.pcs1_cam4_bme280_1_pressure
      - sensor.pcs1_cam5_bme280_1_pressure
      - sensor.pcs1_cam6_bme280_1_pressure

  - platform: average
    name: "pcs1.growth_chamber.average_illuminance"
    duration: 00:00:5
    entities:
      - sensor.pcs1_cam1_bh1750_1_illuminance
      - sensor.pcs1_cam3_bh1750_1_illuminance
      - sensor.pcs1_cam4_bh1750_1_illuminance
      - sensor.pcs1_cam5_bh1750_1_illuminance
      - sensor.pcs1_cam6_bh1750_1_illuminance

  - platform: min_max
    type: max
    name: "pcs1.led1.growth_chamber.max_illuminance"
    entity_ids:
      - sensor.pcs1_cam1_bh1750_1_illuminance
      - sensor.pcs1_cam3_bh1750_1_illuminance
      - sensor.pcs1_cam4_bh1750_1_illuminance
      - sensor.pcs1_cam5_bh1750_1_illuminance
      - sensor.pcs1_cam6_bh1750_1_illuminance

  - platform: average
    name: "pcs1.growth_chamber.average_max_illuminance"
    duration: 00:00:5
    entities:
      - sensor.pcs1_led1_growth_chamber_max_illuminance
