# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages:
    common_device_tracker: !include common/device_tracker.yaml
    
input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off