# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages:
    common_device_tracker: !include common/device_tracker.yaml

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 7
  purge_interval: 1
  commit_interval: 30 

history:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  ssl: false
  max_retries: 3
  default_measurement: state  
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - input_number
      - button
switch:
  - platform: momentary
    name: Camera Snapshots
    mode: on
    toggle_for: 1
    
  - platform: template
    switches:
      red_leds:
        value_template: "{{ is_state('sensor.red_leds', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.pcs1_led1_cc_switch
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.pcs1_led1_cc_switch
    
input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off
  
  activate_looper:
    name: Activate looper
    
  activate_kinematics_automation:
    name: Activate kinematics automation
  
  camera_sequence_taking_photos:
    name: Camera sequence taking photos
    
  activate_led_automation:
    name: Activate led automation
    
# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number:
  
# Example configuration.yaml entry
#sensor:
#  - platform: average
#    name: 'pcs1.led1.dallas_fan_140mm_average.temperature'
#    id: pcs1_led1_dallas_fan_140mm_average_temperature
#    entities:
#      - sensor.pcs1_led1_dallas_fan_140mm_1_temperature
#      - sensor.pcs1_led1_dallas_fan_140mm_2_temperature
#      - sensor.pcs1_led1_dallas_fan_140mm_3_temperature
#      - sensor.pcs1_led1_dallas_fan_140mm_4_temperature
#      
#  - platform: average
#    name: 'pcs1.led1.dallas_fan_80mm_average.temperature'
#    id: pcs1_led1_dallas_fan_80mm_average_temperature
#    entities:
#      - sensor.pcs1_led1_dallas_fan_80mm_1_temperature
#      - sensor.pcs1_led1_dallas_fan_80mm_2_temperature
#      - sensor.pcs1_led1_dallas_fan_80mm_3_temperature
#      - sensor.pcs1_led1_dallas_fan_80mm_4_temperature
#      
#  - platform: average
#    name: 'pcs1.led1.dallas_average.temperature'
#    id: pcs1_led1_dallas_average_temperature
#    entities:
#      - sensor.pcs1_led1_dallas_fan_140mm_mean_temperature
#      - sensor.pcs1_led1_dallas_fan_80mm_mean_temperature