# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Default includes from Home Assistant
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages:
    common_device_tracker: !include common/device_tracker.yaml

#http:
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  
recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 7
  purge_interval: 1
  commit_interval: 30 

history:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pw
  ssl: false
  max_retries: 3
  default_measurement: state  
  measurement_attr: entity_id
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - input_number
      - button
switch:
  - platform: momentary
    name: Camera Snapshots
    mode: on
    toggle_for: 1
      
input_boolean:
  prevent_deep_sleep:
    name: Prevent Deep Sleep
    icon: mdi:sleep-off
    
# Add sliders control to Home Assistant to set position, speed and velocity of the stepper motor
input_number:
    
  led_1_set_level:
    name: led_1.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_2_set_level:
    name: led_2.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_3_set_level:
    name: led_3.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_4_set_level:
    name: led_4.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_5_set_level:
    name: led_5.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_6_set_level:
    name: led_6.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_7_set_level:
    name: led_7.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_8_set_level:
    name: led_8.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_9_set_level:
    name: led_9.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_10_set_level:
    name: led_10.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_11_set_level:
    name: led_11.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
  
  led_12_set_level:
    name: led_12.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider
    
  pwm_fan_set_level:
    name: pwm_fan.set_level
    initial: 0
    min: 0
    max: 1
    step: 0.01
    mode: slider


automation controller_led_1_level:
  - alias: Send level value to led controller 1
    id: led_1_send_level
    trigger:
      platform: state
      entity_id: input_number.led_1_set_level
    action:
      - service: esphome.pcs1_led_led_1_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'
          
automation controller_led_3_level:
  - alias: Send level value to led controller 2
    id: led_3_send_level
    trigger:
      platform: state
      entity_id: input_number.led_3_set_level
    action:
      - service: esphome.pcs1_led_led_3_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_4_level:
  - alias: Send level value to led controller 2
    id: led_4_send_level
    trigger:
      platform: state
      entity_id: input_number.led_4_set_level
    action:
      - service: esphome.pcs1_led_led_4_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_5_level:
  - alias: Send level value to led controller 2
    id: led_5_send_level
    trigger:
      platform: state
      entity_id: input_number.led_5_set_level
    action:
      - service: esphome.pcs1_led_led_5_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_6_level:
  - alias: Send level value to led controller 2
    id: led_6_send_level
    trigger:
      platform: state
      entity_id: input_number.led_6_set_level
    action:
      - service: esphome.pcs1_led_led_6_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_7_level:
  - alias: Send level value to led controller 2
    id: led_7_send_level
    trigger:
      platform: state
      entity_id: input_number.led_7_set_level
    action:
      - service: esphome.pcs1_led_led_7_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_8_level:
  - alias: Send level value to led controller 2
    id: led_8_send_level
    trigger:
      platform: state
      entity_id: input_number.led_8_set_level
    action:
      - service: esphome.pcs1_led_led_8_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_9_level:
  - alias: Send level value to led controller 2
    id: led_9_send_level
    trigger:
      platform: state
      entity_id: input_number.led_9_set_level
    action:
      - service: esphome.pcs1_led_led_9_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_10_level:
  - alias: Send level value to led controller 2
    id: led_10_send_level
    trigger:
      platform: state
      entity_id: input_number.led_10_set_level
    action:
      - service: esphome.pcs1_led_led_10_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_11_level:
  - alias: Send level value to led controller 2
    id: led_11_send_level
    trigger:
      platform: state
      entity_id: input_number.led_11_set_level
    action:
      - service: esphome.pcs1_led_led_11_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_led_12_level:
  - alias: Send level value to led controller 2
    id: led_12_send_level
    trigger:
      platform: state
      entity_id: input_number.led_12_set_level
    action:
      - service: esphome.pcs1_led_led_12_set_level
        data_template:
          led_level: '{{ trigger.to_state.state | float }}'

automation controller_pwm_fan:
  - alias: Send level value to pwm_fan 2
    id: pwm_fan_send_level
    trigger:
      platform: state
      entity_id: input_number.pwm_fan_set_level
    action:
      - service: esphome.pcs1_led_pwm_fan_set_level
        data_template:
          pwm_fan: '{{ trigger.to_state.state | float }}'
