switch:         
  - platform: template
    name: ${device_name_upper}.pump_2
    id: ${device_name}_pump_2
    internal: true
    lambda: |-
       if (id(pump_2_is_on) == true)
         return true;
       else
         return false;
    turn_on_action:
      then:
        - lambda: |-
            if (id(${device_name}_enable).state == true)
            {
              id(${device_name}_pump_2_output).turn_on();
              id(pump_2_is_on) = true;
            }
    turn_off_action:
      then:
        - lambda: |-
            id(${device_name}_pump_2_output).turn_off();
            id(pump_2_is_on) = false;
            
output:
  - platform: gpio
    pin: ${pump_2_pin}
    id: ${device_name}_pump_2_output

globals:
  - id: pump_2_is_on
    type: bool
    restore_value: no
    initial_value: "false"  