binary_sensor:
  - platform: template
    name: "${stepper_motor_id_upper}.active"
    id: ${stepper_motor_id}_active
    lambda: |-
      if (id($stepper_motor_id).current_position != id($stepper_motor_id).target_position) 
      {
        // Motor is still moving
        return true;
      }else 
      {
        // Motor is at target position
        return false;
      }
      
  - platform: gpio
    name: ${device_name_upper}.inductivity_pinoin_wheel_rods
    id: ${device_name}_inductivity_pinoin_wheel_rods
    pin: 
      number: GPIO32
      mode:
        input: true
        pullup: true
      inverted: true
      
  - platform: gpio
    name: ${device_name_upper}.inductivity_home
    id: ${device_name}_inductivity_home
    pin: 
      number: GPIO4
      mode:
        input: true
        pullup: true
      inverted: false