button:
  - platform: template
    name: ${stepper_motor_id_upper}.error.reset_errors
    id: ${stepper_motor_id}_error_reset_errors
    on_press:
      lambda: |-
        get_controller(id(${controller}))->reset_error_code();
        get_controller(id(${controller}))->reset_error_homing_difference();
        get_controller(id(${controller}))->reset_error_pinion_wheel_count();

#binary_sensor:
#  - platform: template
#    name: "${stepper_motor_id_upper}.error.pinionwheel_check"
#    id: ${stepper_motor_id}_error_pinionwheel_check
#    lambda: |-
#      if (get_controller(id(${controller}))->get_pinion_wheel_diff_error())
#      {
#        if (get_controller(id(${controller}))->is_active())
#        {
#            get_controller(id(${controller}))->emergency_stop("Pinionwheel count mismatch", STEPPER_ERROR_PINIONWHEEL_MISMATCH);
#            
#        }
#        if (get_controller(id(${controller}))->homing_is_valid())
#        {
#            get_controller(id(${controller}))->set_homing_invalid();
#            //TODO: auto reset: get_controller(id(${controller}))->reset_error_pinion_wheel_count();
#        }
#        return true;
#      }else
#      {
#        return false;
#      }
#
#  - platform: template
#    name: "${stepper_motor_id_upper}.error.homing_difference_check"
#    id: ${stepper_motor_id}_error_homing_difference_check
#    lambda: |-
#      if (get_controller(id(${controller}))->get_homing_diff_error())
#      {
#        if (get_controller(id(${controller}))->is_active())
#        {
#            get_controller(id(${controller}))->emergency_stop("Homing invalid, lost position", STEPPER_ERROR_HOMING);
#        }
#        get_controller(id(${controller}))->set_homing_invalid();
#        //TODO: auto reset: get_controller(id(${controller}))->reset_error_homing_difference();
#        
#        return true;
#      }else
#      {
#        return false;
#      }