globals:
  - id: stepper_error                
    type: int                           
    restore_value: no                   
    initial_value: "0"  

  - id: stepper_error_none               
    type: int                           
    restore_value: no                   
    initial_value: "0"      
  
  - id: stepper_error_missmatching_full_turn_steps                 
    type: int                           
    restore_value: no                   
    initial_value: "-1" 