globals:
  - id: motor_enabled
    type: bool
    restore_value: no
    initial_value: "false"  
    
  #- id: endless_mode
  #  type: bool
  #  restore_value: no
  #  initial_value: "false"
    
  - id: direction_forward
    type: bool
    restore_value: no
    initial_value: "true"
    
  - id: full_turn_steps
    type: int
    restore_value: yes
    initial_value: ${stepper_initial_full_turn_steps}
  
  - id: requested_target_position
    type: int
    restore_value: no
    initial_value: "0"  
  
  - id: target_position
    type: int
    restore_value: no
    initial_value: "0"
  
  - id: speed
    type: int
    restore_value: no
    initial_value: ${stepper_initial_speed}
  
  - id: acceleration
    type: int
    restore_value: no
    initial_value: ${stepper_acceleration}
  
  - id: deceleration
    type: int
    restore_value: no
    initial_value: ${stepper_deceleration}
    
  - id: step_width
    type: int
    restore_value: no
    initial_value: ${stepper_initial_step_width}
    
  #stepper modes
  - id: stepper_mode                    
    type: int                           
    restore_value: no                   
    initial_value: "0"  
    
  - id: stepper_mode_off                    
    type: int                           
    restore_value: no                   
    initial_value: "0"   

  - id: stepper_mode_ready                   
    type: int                           
    restore_value: no                   
    initial_value: "1"       
    
  - id: stepper_mode_homing                    
    type: int                           
    restore_value: no                   
    initial_value: "2"  
    
  - id: stepper_mode_drive                    
    type: int                           
    restore_value: no                   
    initial_value: "3"  
    
  - id: stepper_mode_target                    
    type: int                           
    restore_value: no                   
    initial_value: "4" 
    
  - id: stepper_mode_step_step_width                    
    type: int                           
    restore_value: no                   
    initial_value: "5" 
    
  - id: stepper_mode_step_30deg                    
    type: int                           
    restore_value: no                   
    initial_value: "6"  
    
  - id: stepper_mode_step_60deg                    
    type: int                           
    restore_value: no                   
    initial_value: "7"  
    
  - id: stepper_mode_step_360deg                    
    type: int                           
    restore_value: no                   
    initial_value: "8"   