#pragma once

#include <esphome.h>

enum eStepperModes
{
	STEPPER_MODE_OFF = 0,
	STEPPER_MODE_READY = 1,
	STEPPER_MODE_HOMING = 2,
	STEPPER_MODE_RANGEESTIMATION = 3,
	STEPPER_MODE_DRIVE = 10,
	STEPPER_MODE_TARGET = 11,
	STEPPER_MODE_STEP_WIDTH = 12,
	STEPPER_MODE_STEP_30DEG = 20,
	STEPPER_MODE_STEP_60DEG = 21,
	STEPPER_MODE_STEP_180DEG = 22,
	STEPPER_MODE_STEP_360DEG = 23
};