# Enable Home Assistant API
api:
  reboot_timeout: 2min
  password: !secret esphome_api_pw

# enable ota updates
ota:
  password: !secret esphome_ota_pw

# Enable logging
logger:
  level: DEBUG
  
captive_portal:

# Example configuration entry
time:
  - platform: sntp
    id: sntp_time