# Dees sleep ESP32 cam to prevent overheating
deep_sleep:
  id: control_deep_sleep
  sleep_duration: ${custom_sleep_duration}
  run_duration: ${custom_run_duration}
  
binary_sensor:
  - platform: homeassistant
    internal: true
    id: prevent_deep_sleep
    name: Prevent Deep Sleep
    entity_id: input_boolean.prevent_deep_sleep
    on_state:
      then:
        if:
          condition:
            - binary_sensor.is_off: prevent_deep_sleep
          then:
            - delay: ${custom_run_duration}
            - if:
                condition:
                  - binary_sensor.is_off: prevent_deep_sleep
                then:
                  - deep_sleep.enter: control_deep_sleep
          else:
            - deep_sleep.prevent: control_deep_sleep
          
interval:
  - interval: 1s
    then:
      if:
        condition:
          - binary_sensor.is_on: prevent_deep_sleep
        then:
          - deep_sleep.prevent: control_deep_sleep