# Dees sleep ESP32 cam to prevent overheating
deep_sleep:
  id: deep_sleep_1
  run_duration: ${custom_run_duration}
  sleep_duration: ${custom_sleep_duration}

mqtt:
  <<: !include mqtt.yaml
  # Messages to control the deep sleep component
  on_message:
  - topic: maintenance/ota_mode/${device_name}
    payload: 'ON'
    then:
    - deep_sleep.prevent: deep_sleep_1
  - topic: maintenance/deep_sleep/${device_name}
    payload: 'ON'
    then:
    - deep_sleep.enter: deep_sleep_1
