# MQTT Broker Settings
mqtt:
  id: ${device_name}_mqtt_client
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_usr
  password: !secret mqtt_pw
  discovery: ${mqtt_discovery}
  port: !secret mqtt_port