# Status LED
light:
  - platform: status_led
    name: ${device_name_upper}.status_led
    id: ${device_name}_status_led
    pin: 
      number: ${status_led_pin}
    internal: true
    
interval:
  - interval: ${status_led_interval_ok}
    then:
      if:
        condition:
          - binary_sensor.is_on: ${device_name}_status
        then:
          - light.turn_on: ${device_name}_status_led
          - delay: 1s
          - light.turn_off: ${device_name}_status_led
  - interval: ${status_led_interval_booting}
    then:
      if:
        condition:
          - binary_sensor.is_off: ${device_name}_status
        then:
          - light.turn_on: ${device_name}_status_led
          - delay: 1s
          - light.turn_off: ${device_name}_status_led