esphome:
  libraries:
     #- ESPAsyncTCP-esphome@1.2.2
     #- ottowinter/ESPAsyncTCP-esphome@^1.2.3
     - me-no-dev/ESPAsyncTCP@^1.2.2
#  includes:
#    - common/stream_server.h
#    - common/stream_server.cpp
#
#uart:
#  id: uart_bus
#  tx_pin: GPIO16
#  rx_pin: GPIO17
#  baud_rate: 9600
#  
#custom_component:
#  - lambda: |-
#      auto stream_server = new StreamServerComponent(id(uart_bus));
#      return {stream_server};


external_components:
  - source: github://oxan/esphome-stream-server

stream_server:
   uart_id: uart_bus
   port: 1234
   
uart:
  id: uart_bus
  tx_pin: GPIO16
  rx_pin: GPIO17
  baud_rate: 9600
  debug:
    #direction: BOTH
    #dummy_receiver: true
    #after:
    #  delimiter: "\n"
    #sequence:
    #  - lambda: UARTDebug::log_string(direction, bytes);

