wifi:
  #ssid: !secret wifi_ap_ssid
  #password: !secret wifi_ap_pw

  ssid: !secret wifi_makeracademy_ssid
  password: !secret wifi_makeracademy_pw
  
  #ssid: !secret wifi_messe_ssid
  #password: !secret wifi_messe_pw
    
    
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$device_name_upper AP"
    password: !secret esphome_fallback_ap_pw
  
  fast_connect: true
  
  #manual_ip:
  #  static_ip: ${settings_static_ip}
  #  gateway: !secret host_wlan0_static_ip
  #  subnet: !secret host_wlan0_netmask
    
captive_portal:

sensor:
  - platform: wifi_signal
    name: "${device_name_upper}.wifi_signal"
    id: ${device_name}_wifi_signal
    update_interval: 60s