substitutions:
  #general settings
  host_name: empty-component
  device_name: empty_component
  device_name_upper: empty.component
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: VERBOSE
  
  # Dallas Temperature Sensors
  sensor_dallas_hub_1_pin: GPIO13
  sensor_dallas_hub_1_name: dallas_hub_1
  sensor_dallas_hub_1_update_interval: 1s
  sensor_dallas_3_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_3_name: dallas_3
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
  
packages:
  common_api: !include common/api.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_restart: !include common/restart.yaml
  sensor_dallas_hub_1: !include sensors/dallas_hub_1.yaml
  #sensor_dallas_1: !include sensors/dallas_3.yaml