substitutions:
  # PCS1 adress range from 101...150
  settings_static_ip_pcs1_cam1:   192.168.99.101
  settings_static_ip_pcs1_cam2:   192.168.99.102
  settings_static_ip_pcs1_cam3:   192.168.99.103
  settings_static_ip_pcs1_cam4:   192.168.99.104
  settings_static_ip_pcs1_cam5:   192.168.99.105
  settings_static_ip_pcs1_cam6:   192.168.99.106
                                  
  settings_static_ip_pcs1_led1:   192.168.99.111
  settings_static_ip_pcs1_led2:   192.168.99.112
  settings_static_ip_pcs1_led3:   192.168.99.113
  settings_static_ip_pcs1_led4:   192.168.99.114
                                  
  settings_static_ip_pcs1_pwm:    192.168.99.120
  settings_static_ip_pcs1_kin:    192.168.99.121
  settings_static_ip_pcs1_as:     192.168.99.122
  settings_static_ip_pcs1_thermo: 192.168.99.123
  settings_static_ip_pcs1_pump:   192.168.99.124
  
  
  
  