substitutions:
  #general settings
  host_name: empty-component
  device_name: empty_component
  device_name_upper: empty.component
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_restart: !include common/restart.yaml