esphome:
  name: esp32stepper
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1663ea9f6d3aa39994e6f3197c54eb0b"

wifi:
  ssid: !secret wifi_ap_ssid
  password: !secret wifi_ap_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Stepper Fallback Hotspot"
    password: "9Ehm1fibFTAi"
  
  fast_connect: true
  
captive_portal: