substitutions:
  device_name: esp32cam_pcs1_unit1
  device_name_upper: ESP32Cam PCS 1 Unit 1
  custom_run_duration: 2min
  custom_sleep_duration: 10min

<<: !include /config/esphome/camera/esp32cam.yaml
#<<: !include /config/esphome/common/deep_sleep.yaml