substitutions:
  device_name_camelcase: esp32camPcs01Unit01
  device_name: esp32cam_pcs01_unit01
  device_name_upper: ESP32Cam PCS 01 Unit 01
  custom_run_duration: 2min
  custom_sleep_duration: 10min

<<: !include /config/esphome/camera/esp32cam.yaml
