substitutions:
  host_name: esp32cam-pcs-1-unit-1
  device_name: esp32cam_pcs_1_unit_1
  device_name_upper: esp32cam PCS 1 Unit 1
  custom_run_duration: "2min"
  custom_sleep_duration: "10min"
  custom_idle_framerate: "0 fps"
  
esphome:
  name: ${device_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  #common_deep_sleep: !include common/deep_sleep.yaml  
  common_restart: !include common/restart.yaml
  camera_esp32cam: !include camera/esp32cam.yaml
  camera_webserver: !include camera/webserver_snapshot.yaml
