esphome:
  name: esp32camera
  platform: ESP32
  board: esp32dev # better stability regarding the idle mode and heating issues
  #board: esp-wrover-kit
  #arduino_version: 1.0.2
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "7de64f407fb8b783986851e62280b35b"

wifi:
  ssid: !secret wifi_ap_ssid
  password: !secret wifi_ap_pw

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Camera Fallback Hotspot"
    password: "dERLMgZIERDN"
  
captive_portal:

esp32_camera_web_server:
  #- port: 8080
  #  mode: stream
  - port: 8081
    mode: snapshot

# Example configuration entry
esp32_camera:
  name: My Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  #resolution: 400x296
  resolution: 640x480
  #resolution: 800x600
  #resolution: 1024x768
  #resolution: 1280x1024
  jpeg_quality: 10
  contrast: 0 # values from -2 ... 2
  brightness: 0 # values from -2 ... 2
  saturation: 0 # values from -2 ... 2
  idle_framerate: 0.1 fps
  vertical_flip: false
  horizontal_mirror: false
  max_framerate: 10 fps
  test_pattern: false