substitutions:
  #general settings
  host_name: pcs1-as
  device_name: pcs1_as
  device_name_upper: pcs1.as
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  
  #I2C Bus
  i2c_bus_a_name: i2c_bus_a
  i2c_bus_a_sda: GPIO23
  i2c_bus_a_scl: GPIO22
  
  #Temp Enable Pin
  enable_rtd_pin: GPIO33
  enable_aux_pin: GPIO27
  enable_ec_pin: GPIO12
  enable_ph_pin: GPIO13
  
  # webserver
  web_server_ota_active: "true"
  
  # EZO Settings
  min_sample_interval_ec: "2000" # 1s
  max_sample_interval_ec: "10000" # 60min
  
  min_sample_interval_ph: "2000" # 1s
  max_sample_interval_ph: "10000" # 60min
  
  min_sample_interval_rtd: "1000" # 1s
  max_sample_interval_rtd: "10000" # 60min
  
  min_sample_interval_ec_tempcomp: "10000" 
  max_sample_interval_ec_tempcomp: "60000"
  
  min_sample_interval_ph_tempcomp: "10000" 
  max_sample_interval_ph_tempcomp: "60000"
  
  max_retry_attempts: "4"
  default_temp_comp_value: "25"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s    

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_restart: !include common/restart.yaml
  common_i2c_bus_a: !include common/i2c_bus_a.yaml
  common_web_server: !include common/web_server.yaml
  #common_api_encryption: !include common/api_encryption.yaml
  as_hydroponics_kit_as_ezo_ec: !include as_hydroponics_kit/as_ezo_ec.yaml
  as_hydroponics_kit_as_ezo_ph: !include as_hydroponics_kit/as_ezo_ph.yaml
  as_hydroponics_kit_as_ezo_rtd: !include as_hydroponics_kit/as_ezo_rtd.yaml

button:

  # ENABLE/DISABLE ALL SENSORS
  - platform: template
    name: ${device_name_upper}.all.enable
    id: ${device_name}_all_enable
    on_press:
      - switch.turn_on: ${device_name}_rtd_enable
      - switch.turn_on: ${device_name}_ec_enable
      - switch.turn_on: ${device_name}_ph_enable
  
  - platform: template
    name: ${device_name_upper}.all.disable
    id: ${device_name}_all_disable
    on_press:
      - switch.turn_off: ${device_name}_rtd_enable
      - switch.turn_off: ${device_name}_ec_enable
      - switch.turn_off: ${device_name}_ph_enable
  
  # ENABLE/DISABLE ALL SENSOR OUTPUTS
  - platform: template
    name: ${device_name_upper}.all.enable_sending_values
    id: ${device_name}_all_enable_sending_values
    on_press:
      - switch.turn_on: ${device_name}_rtd_enable_sending_values
      - switch.turn_on: ${device_name}_ec_enable_sending_values
      - switch.turn_on: ${device_name}_ph_enable_sending_values
  
  - platform: template
    name: ${device_name_upper}.all.disable_sending_values
    id: ${device_name}_all_disable_sending_values
    on_press:
      - switch.turn_off: ${device_name}_rtd_enable_sending_values
      - switch.turn_off: ${device_name}_ec_enable_sending_values
      - switch.turn_off: ${device_name}_ph_enable_sending_values
 
  # ENABLE/DISABLE ALL TEMPCOMP
  - platform: template
    name: ${device_name_upper}.all.enable_tempcomp
    id: ${device_name}_all_enable_tempcomp
    on_press:
      - switch.turn_on: ${device_name}_ec_tempcomp
      - switch.turn_on: ${device_name}_ph_tempcomp
  
  - platform: template
    name: ${device_name_upper}.all.disable_tempcomp
    id: ${device_name}_all_disable_tempcomp
    on_press:
      - switch.turn_off: ${device_name}_ec_tempcomp
      - switch.turn_off: ${device_name}_ph_tempcomp
      