substitutions:
  #general settings
  host_name: pcs1-ledcontroller
  device_name: espexample1
  device_name_upper: pcs1.ledcontroller
  status_led_pin: GPIO33
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s

preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  #common_status_led: !include common/status_led.yaml
  common_restart: !include common/restart.yaml
  
output:
  - platform: ledc
    pin: "GPIO16"
    id: led_panel_1
    frequency: 1000Hz
  
  - platform: ledc
    pin: "GPIO18"
    id: led_panel_2
    frequency: 1000Hz

globals:
  - id: led_1_is_on
    type: bool
    restore_value: no
    initial_value: "false"  
  - id: led_2_is_on
    type: bool
    restore_value: no
    initial_value: "false"  
    
button:
  - platform: template
    name: led_1_0_percent
    id: led_1_0_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_1
           level: "0%" 
  
  - platform: template
    name: led_1_10_percent
    id: led_1_10_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_1
           level: "10%" 
           
  - platform: template
    name: led_1_50_percent
    id: led_1_50_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_1
           level: "50%" 
           
  - platform: template
    name: led_1_90_percent
    id: led_1_90_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_1
           level: "90%" 
           
  - platform: template
    name: led_1_100_percent
    id: led_1_100_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_1
           level: "100%" 
  - platform: template
    name: led_2_0_percent
    id: led_2_0_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_2
           level: "0%" 
  
  - platform: template
    name: led_2_10_percent
    id: led_2_10_percent_2
    on_press:
      then:
        - output.set_level:
           id: led_panel_2
           level: "10%" 
           
  - platform: template
    name: led_2_50_percent
    id: led_2_50_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_2
           level: "50%" 
           
  - platform: template
    name: led_2_90_percent
    id: led_2_90_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_2
           level: "90%" 
           
  - platform: template
    name: led_2_100_percent
    id: led_2_100_percent
    on_press:
      then:
        - output.set_level:
           id: led_panel_2
           level: "100%" 
switch:
  - platform: template
    name: turn_on_led_1
    id: turn_on_led_1
    lambda: |-
       if (id(led_1_is_on) == true)
         return true;
       else
         return false;
    turn_on_action:
      then:
        - output.turn_on: led_panel_1
        - globals.set:
            id: led_1_is_on
            value: "true"
    turn_off_action:
      then:
        - output.turn_off: led_panel_1  
        - globals.set:
           id: led_1_is_on
           value: "false"     

  - platform: template
    name: turn_on_led_2
    id: turn_on_led_2
    lambda: |-
       if (id(led_2_is_on) == true)
         return true;
       else
         return false;
    turn_on_action:
      then:
        - output.turn_on: led_panel_2
        - globals.set:
            id: led_2_is_on
            value: "true"
    turn_off_action:
      then:
        - output.turn_off: led_panel_2 
        - globals.set:
           id: led_2_is_on
           value: "false"               
        
api:
  services:      
    - service: led_1_set_level
      variables:
        led_level: float
      then:
        - logger.log: "Set led led_1_level"
        - output.set_level:
           id: led_panel_1
           level: !lambda 'return led_level;'
           
    - service: led_2_set_level
      variables:
        led_level: float
      then:
        - logger.log: "Set led led_2_level"
        - output.set_level:
           id: led_panel_2
           level: !lambda 'return led_level;'