substitutions:
  #general settings
  host_name: pcs1-as
  device_name: pcs1_as
  device_name_upper: pcs1.as
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  
  #I2C Bus
  i2c_bus_a_name: i2c_bus_a
  i2c_bus_a_sda: GPIO23
  i2c_bus_a_scl: GPIO22

  # webserver
  web_server_ota_active: "true"
  
  # EZO settings
  max_retry_attempts: "4"
  default_temp_comp_value: "25"
  
  # EZO Enable Pins
  enable_rtd_pin: GPIO33
  enable_ec_pin: GPIO12
  enable_ph_pin: GPIO13
  
  # EZO sample intervals
  min_sample_interval_ec: "2000" # 1s
  max_sample_interval_ec: "10000" # 60min
  
  min_sample_interval_ph: "2000" # 1s
  max_sample_interval_ph: "10000" # 60min
  
  min_sample_interval_rtd: "1000" # 1s
  max_sample_interval_rtd: "10000" # 60min
  
  min_sample_interval_ec_tempcomp: "10000" 
  max_sample_interval_ec_tempcomp: "60000"
  
  min_sample_interval_ph_tempcomp: "10000" 
  max_sample_interval_ph_tempcomp: "60000"

esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s    
  
packages:
  #common_mqtt: !include common/mqtt.yaml
  common_api: !include common/api.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_restart: !include common/restart.yaml
  common_i2c_bus_a: !include common/i2c_bus_a.yaml
  common_web_server: !include common/web_server.yaml
  #common_api_encryption: !include common/api_encryption.yaml
  as_hydroponics_kit_as_ezo: !include as_hydroponics_kit/as_ezo.yaml