substitutions:
  #general settings
  host_name: ofai-pcs1-kin
  device_name: pcs1_kin
  device_name_upper: pcs1.kin
  status_led_pin: "GPIO13"
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: VERBOSE
  settings_flash_write_interval: 1min
  
  #stepper settings
  stepper_step_pin: GPIO27  # GPIO26
  stepper_dir_pin: GPIO26   # GPIO27
  stepper_sleep_pin: GPIO12 
  stepper_enable_pin: GPIO04 #GPIO25
  stepper_diag_pin_1: GPIO17 #GPIO18
  stepper_diag_pin_2: GPIO18 #GPIO17      #
  stepper_diag_pin_3: GPIO19      #
  stepper_invert_direction: "false" 
  stepper_max_speed: "1000"
  stepper_max_speed_uncalibrated: "3000"
  stepper_max_acceleration: "2000"
  stepper_max_deceleration: "2000"
  stepper_initial_speed: "400"
  stepper_acceleration: "500"     #"inf"
  stepper_deceleration: "1000"    #"inf"
  stepper_initial_step_width: "2000"
  stepper_update_interval_ms: "1000"
  stepper_error_homing_difference: "1000"
  stepper_max_turns_per_hour: "18"
  stepper_initial_turns_per_hour: "3"
  
  # homing settings
  homing_high_speed: "800"
  homing_mid_speed: "150"
  homing_low_speed: "75"
  
  #fans
  fan_pin: GPIO23 #GPIO18
  fan_frequency: "10kHz"
  
  # Proximity Switch settings
  sensor_proximity_switch_pinion_wheel_pin: GPIO32 #PS_02
  sensor_proximity_switch_home_pin: GPIO16  # PS_03
  sensor_proximity_switch_global_home_pin: GPIO33 # PS_01
  
  # Stepper Sensor value settings
  sensor_update_interval_realtime: 0.1s
  sensor_update_interval_fast: 1s
  sensor_update_interval_mid: 10s
  sensor_update_interval_slow: 60s
  
  sensor_update_interval_realtime_ms: "100"
  sensor_update_interval_fast_ms: "1000"
  sensor_update_interval_mid_ms: "10000"
  sensor_update_interval_slow_ms: "60000"
  
  # Current Sensor (analog In)
  sensor_current_pin: GPIO34
  
  # Dallas Temperature Sensors
  sensor_dallas_hub_1_pin: GPIO25
  sensor_dallas_hub_1_name: dallas_hub_1
  sensor_dallas_hub_1_update_interval: 1s
  sensor_dallas_4_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_4_name: dallas_4
  sensor_dallas_4_force_update: "false"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
           
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_boot_finished: !include /config/esphome/esphome-common/boot_finished.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  #common_status_led: !include /config/esphome/esphome-common/status_led.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  stepper_a4988: !include /config/esphome/esphome-stepper/a4988.yaml
  stepper_diag_1: !include /config/esphome/esphome-stepper/tmc2209_addon.yaml
  stepper_diag_2: !include /config/esphome/esphome-stepper/stepper_diag_1.yaml
  stepper_diag_3: !include /config/esphome/esphome-stepper/stepper_diag_2.yaml
  stepper_tmc2209_addon: !include /config/esphome/esphome-stepper/stepper_diag_3.yaml
  stepper_sensor: !include /config/esphome/esphome-stepper/sensor.yaml
  error_handling: !include /config/esphome/esphome-stepper/error_handling.yaml
  error_connection_handling: !include /config/esphome/esphome-stepper/error_connection_handling.yaml
  sensor_current: !include /config/esphome/esphome-sensors/current.yaml
  sensor_dallas_hub_1: !include /config/esphome/esphome-sensors/dallas_hub_1.yaml
  sensor_dallas_1: !include /config/esphome/esphome-sensors/dallas_4.yaml
  sensor_dallas_adress_config: !include /config/esphome/esphome-sensors/dallas_adress_config.yaml