substitutions:
  #general settings
  host_name: pcs1-espcontroller1
  device_name: pcs1_espcontroller1
  device_name_upper: pcs1.espcontroller1
  status_led_pin: "GPIO13"
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  
  #stepper settings
  stepper_step_pin: GPIO26
  stepper_dir_pin: GPIO27
  stepper_sleep_pin: GPIO12 # GPIO25
  stepper_enable_pin: GPIO25 #GPIO33  #GPIO15
  stepper_diag_pin_1: GPIO18      #GPIO33
  stepper_diag_pin_2: GPIO17      #
  stepper_diag_pin_3: GPIO19      #
  stepper_invert_direction: "false" 
  stepper_max_speed: "12000"
  stepper_max_acceleration: "2000"
  stepper_max_deceleration: "2000"
  stepper_initial_speed: "500"
  stepper_acceleration: "1000"     #"inf"
  stepper_deceleration: "1000"    #"inf"
  stepper_initial_step_width: "2000"
  stepper_update_interval_ms: "1000"
  stepper_error_homing_difference: "1000"
  
  
  # homing settings
  homing_high_speed: "12000"
  homing_mid_speed: "250"
  homing_low_speed: "100"
  
  #fans
  fan_pin: GPIO21 #GPIO18
  
  # sensor settings
  sensor_proximity_switch_pinion_wheel_pin: GPIO32
  sensor_proximity_switch_home_pin: GPIO16
  sensor_proximity_switch_global_home_pin: GPIO33
  
  sensor_update_interval_realtime: 0.1s
  sensor_update_interval_fast: 1s
  sensor_update_interval_mid: 10s
  sensor_update_interval_slow: 60s
  
  sensor_update_interval_realtime_ms: "100"
  sensor_update_interval_fast_ms: "1000"
  sensor_update_interval_mid_ms: "10000"
  sensor_update_interval_slow_ms: "60000"
  
  sensor_current_pin: GPIO35
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min

packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_status_led: !include common/status_led.yaml
  common_restart: !include common/restart.yaml
  stepper_a4988: !include stepper/a4988.yaml
  stepper_tmc2209_addon: !include stepper/tmc2209_addon.yaml
  stepper_sensor: !include stepper/sensor.yaml
  error_handling: !include stepper/error_handling.yaml
  sensor_current: !include sensors/current.yaml