substitutions:
  #general settings
  host_name: pcs1-espcontroller1
  device_name: pcs1_espcontroller1
  device_name_upper: pcs1.espcontroller1
  status_led_pin: "GPIO13"
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  
  #stepper settings
  stepper_step_pin: GPIO26
  stepper_dir_pin: GPIO27
  stepper_sleep_pin: GPIO32 # GPIO25
  stepper_enable_pin: GPIO25 #GPIO33  #GPIO15
  stepper_sleep_state_pin: GPIO33 #GPIO14
  stepper_diag_pin_1: GPIO18      #GPIO33
  stepper_diag_pin_2: GPIO5      #
  stepper_diag_pin_3: GPIO19      #
  stepper_invert_direction: "false" 
  stepper_max_speed: "12000"
  stepper_max_acceleration: "2000"
  stepper_max_deceleration: "2000"
  stepper_initial_speed: "500"
  stepper_acceleration: "1000"     #"inf"
  stepper_deceleration: "1000"    #"inf"
  stepper_initial_step_width: "2000"
  stepper_initial_full_turn_steps: "764586"
  stepper_error_pinion_wheels: "2"
  stepper_error_full_turn_steps: "0.05"
  stepper_update_interval_ms: "1000"
  # homing settings
  homing_high_speed: "12000"
  homing_mid_speed: "250"
  homing_low_speed: "100"

  # kinematics
  kinematics_plant_gear_teeth: "12"
  kinematics_pinion_wheel_rods_upper: "40"
  kinematics_pinion_wheel_rods_lower: "64"
  kinematics_transmission_gear_big_teeth: "15"
  kinematics_transmission_gear_small_teeth: "140"
  kinematics_steps_per_rotation: "200"
  kinematics_microsteps_per_step: "64"
  kinematics_motor_gear_teeth: "10"
  
  #fans
  fan_pin: GPIO21 #GPIO18
  
  # sensor settings
  sensor_proximity_switch_pinion_wheel_pin: GPIO15 
  sensor_proximity_switch_home_pin: GPIO4
  sensor_proximity_switch_global_home_pin: GPIO2
  sensor_update_interval_realtime: 0.1s
  sensor_update_interval_fast: 1s
  sensor_update_interval_mid: 10s
  sensor_update_interval_slow: 60s
  
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min

packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_status_led: !include common/status_led.yaml
  common_restart: !include common/restart.yaml
  stepper_a4988: !include stepper/a4988.yaml
  stepper_tmc2209_addon: !include stepper/tmc2209_addon.yaml
  stepper_homing: !include stepper/homing.yaml
  stepper_pioniowheel_counter: !include stepper/pioniowheel_counter.yaml
  stepper_sensor: !include stepper/sensor.yaml
  #stepper_error_handling: !include stepper/error_handling.yaml