substitutions:
  #general settings
  host_name: ofai-pcs1-led2
  device_name: pcs1_led2
  device_name_upper: pcs1.led2
  status_led_pin: GPIO33
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  activate_fast_connect: "true"
  api_reboot_timeout: "2min"
  
  # Dallas settings
  sensor_dallas_hub_1_pin: GPIO25
  sensor_dallas_hub_1_name: dallas_hub_1
  sensor_dallas_hub_1_update_interval: 1s
  sensor_dallas_1_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_1_name: dallas_1
  sensor_dallas_2_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_2_name: dallas_2
  
  # Hall Sensor settings
  sensor_current_hall_1_pin: GPIO35
  sensor_current_hall_1_name: hall_a
  
  sensor_current_hall_2_pin: GPIO34
  sensor_current_hall_2_name: hall_b
  
  # LED Settings
  pwm_led_frequency: "1000Hz"
  
  pwm_led_cc_1_name: cc_a_1_630nm
  pwm_led_cc_2_name: cc_a_2_630nm
  pwm_led_cc_3_name: cc_a_3_630nm
  pwm_led_cc_4_name: cc_a_4_630nm
  pwm_led_cc_5_name: cc_b_1_630nm
  pwm_led_cc_6_name: cc_b_2_630nm
  pwm_led_cc_7_name: cc_b_3_630nm
  pwm_led_cc_8_name: cc_b_4_630nm
  
  pwm_led_cc_1_max_value: "0.2"
  pwm_led_cc_2_max_value: "0.2"
  pwm_led_cc_3_max_value: "0.2"
  pwm_led_cc_4_max_value: "0.2"
  pwm_led_cc_5_max_value: "0.2"
  pwm_led_cc_6_max_value: "0.2"
  pwm_led_cc_7_max_value: "0.2"
  pwm_led_cc_8_max_value: "0.2"
  
button:
  - platform: template
    name: ${device_name}.cc_on
    id: ${device_name}_cc_on
    on_press:
      - button.press: ${device_name}_cc_a_on
      - button.press: ${device_name}_cc_b_on
  
  - platform: template
    name: ${device_name}.cc_off
    id: ${device_name}_cc_off
    on_press:
      - button.press: ${device_name}_cc_a_off
      - button.press: ${device_name}_cc_b_off
      
  - platform: template
    name: ${device_name}.cc_a_on
    id: ${device_name}_cc_a_on
    on_press:
      - light.turn_on: ${device_name}_${pwm_led_cc_1_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_2_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_3_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_4_name}
  
  - platform: template
    name: ${device_name}.cc_a_off
    id: ${device_name}_cc_a_off
    on_press:
      - light.turn_off: ${device_name}_${pwm_led_cc_1_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_2_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_3_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_4_name}

  - platform: template
    name: ${device_name}.cc_b_on
    id: ${device_name}_cc_b_on
    on_press:
      - light.turn_on: ${device_name}_${pwm_led_cc_5_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_6_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_7_name}
      - light.turn_on: ${device_name}_${pwm_led_cc_8_name}
  
  - platform: template
    name: ${device_name}.cc_b_off
    id: ${device_name}_cc_b_off
    on_press:
      - light.turn_off: ${device_name}_${pwm_led_cc_5_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_6_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_7_name}
      - light.turn_off: ${device_name}_${pwm_led_cc_8_name}
      
globals:
  - id: ${device_name}_leds_on
    type: bool
    restore_value: no
    initial_value: "false"  

  - id: ${device_name}_cc_a_is_on
    type: bool
    restore_value: no
    initial_value: "false"  
    
  - id: ${device_name}_cc_b_is_on
    type: bool
    restore_value: no
    initial_value: "false"  
    
switch:       
  - platform: template
    name: ${device_name}.cc_a_switch
    id: ${device_name}_cc_a_switch
    lambda: |-
      return id(${device_name}_cc_a_is_on);
    turn_on_action:
      - button.press: ${device_name}_cc_a_on
      - globals.set:
          id: ${device_name}_cc_a_is_on
          value: "true"
    turn_off_action:
      - button.press: ${device_name}_cc_a_off
      - globals.set:
          id: ${device_name}_cc_a_is_on
          value: "false"
  
  - platform: template
    name: ${device_name}.cc_b_switch
    id: ${device_name}_cc_b_switch
    lambda: |-
      return id(${device_name}_cc_b_is_on);
    turn_on_action:
      - button.press: ${device_name}_cc_b_on
      - globals.set:
          id: ${device_name}_cc_b_is_on
          value: "true"
    turn_off_action:
      - button.press: ${device_name}_cc_b_off
      - globals.set:
          id: ${device_name}_cc_b_is_on
          value: "false"
          
  - platform: template
    name: ${device_name}.cc_switch
    id: ${device_name}_cc_switch
    lambda: |-
      return id(${device_name}_leds_on);
    turn_on_action:
      - switch.turn_on: ${device_name}_cc_a_switch
      - switch.turn_on: ${device_name}_cc_b_switch
      - globals.set:
          id: ${device_name}_leds_on
          value: "true"
    turn_off_action:
      - switch.turn_off: ${device_name}_cc_a_switch
      - switch.turn_off: ${device_name}_cc_b_switch
      - globals.set:
          id: ${device_name}_leds_on
          value: "false"
          
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  #board: nodemcu-32s
  
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  sensor_current_hall_1: !include /config/esphome/esphome-sensors/current_hall_1.yaml
  sensor_current_hall_2: !include /config/esphome/esphome-sensors/current_hall_2.yaml
  pwm_led_gpio_config: !include /config/esphome/esphome-pwm/led_cc_gpio_config.yaml
  pwm_led_1: !include /config/esphome/esphome-pwm/led_cc_1.yaml
  pwm_led_2: !include /config/esphome/esphome-pwm/led_cc_2.yaml
  pwm_led_3: !include /config/esphome/esphome-pwm/led_cc_3.yaml
  pwm_led_4: !include /config/esphome/esphome-pwm/led_cc_4.yaml
  pwm_led_5: !include /config/esphome/esphome-pwm/led_cc_5.yaml
  pwm_led_6: !include /config/esphome/esphome-pwm/led_cc_6.yaml
  pwm_led_7: !include /config/esphome/esphome-pwm/led_cc_7.yaml
  pwm_led_8: !include /config/esphome/esphome-pwm/led_cc_8.yaml