substitutions:
  host_name: pcs1-espcontroller1
  device_name: pcs1_espcontroller1
  device_name_upper: pcs1.espcontroller1
  status_led_pin: "GPIO13"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min

packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_status_led: !include common/status_led.yaml
  common_restart: !include common/restart.yaml
  stepper_a4988: !include stepper/a4988.yaml
  stepper_button: !include stepper/button.yaml