substitutions:
  #general settings
  host_name: pcs1-pwm
  device_name: pcs1_pwm
  device_name_upper: pcs1.pwm
  status_led_pin: GPIO33
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: VERBOSE
  settings_flash_write_interval: 1min
  
  # Dallas settings
  sensor_dallas_hub_1_pin: GPIO13
  sensor_dallas_hub_1_name: dallas_hub_1
  sensor_dallas_hub_1_update_interval: 1s
  sensor_dallas_1_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_1_name: dallas_1
  sensor_dallas_2_hub_id: ${sensor_dallas_hub_1_name}
  sensor_dallas_2_name: dallas_2
  
  # LED Settings
  pwm_led_frequency: "1000Hz"

  pwm_led_cc_9_name: cc_a_1_white
  pwm_led_cc_10_name: cc_a_2_white
  pwm_led_cc_11_name: cc_a_3_520nm
  
  # PWM settings
  pwm_fan_frequency: "1000Hz"
  pwm_fan_pin: "GPIO32"
  pwm_fan_name: cc_a_4_fan
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev
  
packages:
  common_api: !include common/api.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_restart: !include common/restart.yaml
  sensor_dallas_hub_1: !include sensors/dallas_hub_1.yaml
  sensor_dallas_1: !include sensors/dallas_1.yaml
  sensor_dallas_2: !include sensors/dallas_2.yaml
  pwm_led_gpio_config: !include pwm/led_cc_gpio_config.yaml
  pwm_fan: !include pwm/fan.yaml
  pwm_led_9: !include pwm/led_cc_9.yaml
  pwm_led_10: !include pwm/led_cc_10.yaml
  pwm_led_11: !include pwm/led_cc_11.yaml