substitutions:
  #general settings
  host_name: ofai-pcs1-pump
  device_name: pcs1_pump
  device_name_upper: pcs1.pump
  status_led_pin: "GPIO13"
  status_led_interval_ok: 10s
  status_led_interval_booting: 3s
  settings_log_level: DEBUG
  settings_flash_write_interval: 1min
  activate_fast_connect: "true"
  api_reboot_timeout: "2min"
  
  # pump settings
  pump_1_pin: "GPIO32"
  pump_2_pin: "GPIO33" 
  pump_interval_max: "720"  
  pump_interval_initial: "30"  
  pump_duration_max: "600"
  pump_duration_initial: "5"
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
  level: DEBUG
  
preferences:
  flash_write_interval: 1min
           
packages:
  common_api: !include /config/esphome/esphome-common/api.yaml
  common_base: !include /config/esphome/esphome-common/base.yaml
  common_boot_finished: !include /config/esphome/esphome-common/boot_finished.yaml
  common_status: !include /config/esphome/esphome-common/status.yaml
  common_restart: !include /config/esphome/esphome-common/restart.yaml
  #common_api_connection_watchdog: !include /config/esphome/esphome-common/api_connection_watchdog.yaml
  pumps: !include /config/esphome/esphome-pump/pumps.yaml