substitutions:
  host_name: pcs1-espcam1
  device_name: pcs1_espcam1
  device_name_upper: pcs1.espcam1
  status_led_pin: GPIO12
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_status: !include common/status.yaml
  common_status_led: !include common/status_led.yaml
  common_restart: !include common/restart.yaml
  camera_esp32cam: !include camera/esp32cam.yaml
  #camera_esp32cam: !include camera/sensors.yaml
  #camera_webserver: !include camera/webserver_snapshot.yaml