substitutions:
  host_name: pcs-1-esp-1
  device_name: pcs_1_esp_1
  device_name_upper: PCS-1 ESP-1
  custom_idle_framerate: "0 fps"
  #custom_adress_bme280: 0x77
  
esphome:
  name: ${host_name}
  platform: ESP32
  board: esp32dev

preferences:
  flash_write_interval: 1min
  
packages:
  common_wifi: !include common/wifi.yaml
  common_base: !include common/base.yaml
  common_restart: !include common/restart.yaml
  camera_esp32cam: !include camera/esp32cam.yaml
  #camera_webserver: !include camera/webserver_snapshot.yaml